SELECT 
    id,
    responder,
    survey_id,
    date,
    JSON_UNQUOTE(JSON_EXTRACT(results, '$.SecurityTopPriority')) AS SecurityTopPriority,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.adoptingSecureTechnology')) AS adoptingSecureTechnology,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.challengesOfDrivingSecurityInvestments')) AS challengesOfDrivingSecurityInvestments,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.deployableDevicesVulnerability')) AS deployableDevicesVulnerability,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.DSbD')) AS DSbD,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.DSbDsignificancy')) AS DSbDsignificancy,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.DSbDtechnologySolution')) AS DSbDtechnologySolution,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.hardwareVulnerability')) AS hardwareVulnerability,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.improvingSecurityJustfication')) AS improvingSecurityJustfication,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.incidentConcerns')) AS incidentConcerns,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.investmentInCybersecurity')) AS investmentInCybersecurity,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.ITbudget')) AS ITbudget,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.knowledgeInSecurebyDefault')) AS knowledgeInSecurebyDefault,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.levelofPrioritytoCybersecurity')) AS levelofPrioritytoCybersecurity,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.natureofDataUsed')) AS natureofDataUsed,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.obstaclesToDSbD')) AS obstaclesToDSbD,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.priorExperienceOfSecurityIncidents')) AS priorExperienceOfSecurityIncidents,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.prioritizationOfSecuritybyOtherParts')) AS prioritizationOfSecuritybyOtherParts,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.productsCompromised')) AS productsCompromised,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.promotionSecurity')) AS promotionSecurity,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.purchasingTechnology')) AS purchasingTechnology,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.rangeofIncidents')) AS rangeofIncidents,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.ratingOrganizationPriority')) AS ratingOrganizationPriority,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.reducingVulnerabilities')) AS reducingVulnerabilities,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.reportingofIncidents')) AS reportingofIncidents,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.resilienceOfDevices')) AS resilienceOfDevices,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.securebyDefault')) AS securebyDefault,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.secureTechnologies')) AS secureTechnologies,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.securityAspectsProducts')) AS securityAspectsProducts,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.securityAssuranceProcurement')) AS securityAssuranceProcurement,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.securityAssurances')) AS securityAssurances,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.securityAttention')) AS securityAttention,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.securityHighPriority')) AS securityHighPriority,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.securityInvestmentbyThreats')) AS securityInvestmentbyThreats,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.securityInvestmentMotivation')) AS securityInvestmentMotivation,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.securityInvestmentsToChanges')) AS securityInvestmentsToChanges,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.selectingDSbD')) AS selectingDSbD,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.softwareVulnerability')) AS softwareVulnerability,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.spendingOnMoreSecureDevice')) AS spendingOnMoreSecureDevice,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.technogyBasedDisruption')) AS technogyBasedDisruption,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.technologyContext')) AS technologyContext,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.technologyDevices')) AS technologyDevices,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.technologyTypes')) AS technologyTypes,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.technologyUsage')) AS technologyUsage,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.upperManagement')) AS upperManagement,
    JSON_UNQUOTE(JSON_EXTRACT(results,'$.WillingnessToImproveCybersecurity')) AS WillingnessToImproveCybersecurity


    -- Add more fields as needed
FROM 
    results;    
    